### ISSUE TITLE
device logic failing in colab

### ISSUE THREAD

**Issue by amazingvince** [impira/docquery#4]
Traceback (most recent call last):
  File "/usr/local/bin/docquery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/docquery/cmd/__main__.py", line 59, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/docquery/cmd/scan.py", line 47, in main
    nlp = get_pipeline(args.checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/docquery/pipeline.py", line 79, in get_pipeline
    **pipeline_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/pipelines/__init__.py", line 767, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docquery/ext/pipeline.py", line 87, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/pipelines/base.py", line 768, in __init__
    self.device = device if framework == "tf" else torch.device("cpu" if device < 0 else f"cuda:{device}")
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by ankrgyl** [comment]
Eek, I'll take a look and report back shortly. Thanks for filing.

**Comment by amazingvince** [comment]
This works:
 ` if device is None:`
 `       device = 0 if torch.cuda.is_available() else -1`

**Comment by amazingvince** [comment]
I still think this might be the best way is you are not exposing the ability to choose a gpu directly: `device_map="auto"`

**Comment by ankrgyl** [comment]
i went with the first approach for now! https://github.com/impira/docquery/commit/3073a4953dbc7643b3c299bcbd313ed7a809afc7.
 
Thanks for the tip.
