### ISSUE TITLE
Exception: You cannot use ``pop`` on a ModelOutput instance.

### ISSUE THREAD

**Issue by gmpetrov** [impira/docquery#60]
Hello 

I'm getting the following error when trying the google colab demo 
https://colab.research.google.com/github/amazingvince/docqa/blob/updating_colab/docquery_example.ipynb
(Same issue on my m1 macbook)

```bash
!docquery scan "who authored this paper?" https://arxiv.org/pdf/2101.07597.pdf

023-01-30 19:00:54,639 ERROR: Failed while processing https://arxiv.org/pdf/2101.07597.pdf on question: 'who authored this paper?'
Traceback (most recent call last):
  File "/usr/local/bin/docquery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/docquery/cmd/__main__.py", line 61, in main
    return args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/docquery/cmd/scan.py", line 95, in main
    response = nlp(question=q, **d.context)
  File "/usr/local/lib/python3.8/dist-packages/docquery/ext/pipeline_document_question_answering.py", line 232, in __call__
    return super().__call__({"question": question, "pages": normalized_images}, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 1076, in __call__
    return next(
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 291, in __next__
    is_last = item.pop("is_last")
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/generic.py", line 281, in pop
    raise Exception(f"You cannot use ``pop`` on a {self.__class__.__name__} instance.")
Exception: You cannot use ``pop`` on a ModelOutput instance.
```

**Comment by logan-markewich** [comment]
looks like an issue with the transformers package

Maybe try updating to the latest transformers version? 
`!pip install --upgrade transformers`

Alternatively, also try with the transformers version listed in the requirements.txt if you don't already have it (although I think the reqs file is outdated)

**Comment by gmpetrov** [comment]
Thx for your reply. Still getting the same error with the latest version of the transformers package (4.26.0). 

https://colab.research.google.com/drive/1Z_ujjVo3Neaz7aBLOIhELq0sbu0yOehe?usp=sharing

Are you able to reproduce the error on your side? 

```python
!pip install --upgrade transformers 

import transformers

print(transformers.__version__)

!docquery scan "who authored this paper?" https://arxiv.org/pdf/2101.07597.pdf

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: transformers in /usr/local/lib/python3.8/dist-packages (4.26.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /usr/local/lib/python3.8/dist-packages (from transformers) (0.12.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (2022.6.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.8/dist-packages (from transformers) (0.13.2)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from transformers) (2.25.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.8/dist-packages (from transformers) (4.64.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from transformers) (3.9.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from transformers) (6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from transformers) (21.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (1.21.6)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0,>=0.11.0->transformers) (4.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (4.0.0)
4.26.0
document-question-answering is already registered. Overwriting pipeline for task document-question-answering...
Downloading (…)/ff904df/config.json: 100% 789/789 [00:00<00:00, 101kB/s]
Downloading (…)okenizer_config.json: 100% 315/315 [00:00<00:00, 120kB/s]
Downloading (…)e/ff904df/vocab.json: 100% 798k/798k [00:00<00:00, 6.57MB/s]
Downloading (…)e/ff904df/merges.txt: 100% 456k/456k [00:00<00:00, 4.59MB/s]
Downloading (…)904df/tokenizer.json: 100% 1.36M/1.36M [00:00<00:00, 9.73MB/s]
Downloading (…)cial_tokens_map.json: 100% 239/239 [00:00<00:00, 66.6kB/s]
Downloading (…)"pytorch_model.bin";: 100% 511M/511M [00:04<00:00, 123MB/s]
2023-01-31 22:13:02,779 ERROR: Failed while processing https://arxiv.org/pdf/2101.07597.pdf on question: 'who authored this paper?'
Traceback (most recent call last):
  File "/usr/local/bin/docquery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/docquery/cmd/__main__.py", line 61, in main
    return args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/docquery/cmd/scan.py", line 95, in main
    response = nlp(question=q, **d.context)
  File "/usr/local/lib/python3.8/dist-packages/docquery/ext/pipeline_document_question_answering.py", line 232, in __call__
    return super().__call__({"question": question, "pages": normalized_images}, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 1076, in __call__
    return next(
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 291, in __next__
    is_last = item.pop("is_last")
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/generic.py", line 281, in pop
    raise Exception(f"You cannot use ``pop`` on a {self.__class__.__name__} instance.")
Exception: You cannot use ``pop`` on a ModelOutput instance.
```

**Comment by logan-markewich** [comment]
Oh weird. Yea I tried a few things on colab, using `!pip install transformers==4.24.0` after installing everything normally ended up working for me. 
![image](https://user-images.githubusercontent.com/22285038/215908766-8b850ec1-5d51-438e-8496-2a0d69230889.png)


I'll leave it up to the authors of the repo to figure out if this is a transformers issue or an issue with how they are using transformers lol

**Comment by floridatechnologies** [comment]
try this
pip install git+https://github.com/impira/transformers@153d1361c7dcc91c7735cae73e1f594cfcab3e21

**Comment by gmpetrov** [comment]
> Oh weird. Yea I tried a few things on colab, using `!pip install transformers==4.24.0` after installing everything normally ended up working for me. ![image](https://user-images.githubusercontent.com/22285038/215908766-8b850ec1-5d51-438e-8496-2a0d69230889.png)
> 
> I'll leave it up to the authors of the repo to figure out if this is a transformers issue or an issue with how they are using transformers lol

Thx, I don't understand why, but it worked!
