### ISSUE TITLE
already installed tensort not working still

### ISSUE THREAD

**Issue by Achinth04** [impira/docquery#67]
2023-06-17 18:30:01.207852: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
i am working on google collab

i also get an error when i use pipeline.getpipline
says its an attribute error and that the object doesn't have such a method

**Comment by AnuragJha003** [comment]
Did you get any solution for this issue? I am also facing the same issue

**Comment by pararthdave** [comment]
> 2023-06-17 18:30:01.207852: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT i am working on google collab
> 
> i also get an error when i use pipeline.getpipline says its an attribute error and that the object doesn't have such a method

Hi that is just a warning, I had to downgrade my transformer version to 4.23 and it started working in my case

**Comment by shikhasingh1797** [comment]
hii
(doc) PS D:\docquery> docquery scan "What is the #1 post's title?" website.html 
>> 
document-question-answering is already registered. Overwriting pipeline for task document-question-answering...
2023-11-17 08:06:58,947 INFO: Loading website.html
Traceback (most recent call last):
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\N_B\Miniconda3\envs\doc\Scripts\docquery.exe\__main__.py", line 7, in <module>
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\cmd\__main__.py", line 61, in main
    return args.func(args)
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\cmd\scan.py", line 67, in main
    docs.append((p, load_document(str(p), ocr_reader=args.ocr, use_embedded_text=args.use_embedded_text)))
  File "pydantic\decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic\decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic\decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\document.py", line 261, in load_document
    return WebDocument(fpath)
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\document.py", line 193, in __init__
    self.driver = get_webdriver()
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\web.py", line 128, in get_webdriver
    WEB_DRIVER = WebDriver()
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\web.py", line 34, in __init__
    "Web imports are unavailable. You must install the [web] extra and chrome or" " chromium system-wide."
ValueError: Web imports are unavailable. You must install the [web] extra and chrome or chromium system-wide.
(doc) PS D:\docquery>

**Comment by AnuragJha003** [comment]
@shikhasingh1797  
Try downgrading the Transformer version to 4.23 and restarting the environment. It worked in my case. 
You can also refer to the code in this link as to the situation in which the error is coming so maybe u can correct it from there . [https://github.com/impira/docquery/blob/main/src/docquery/web.py](url)

**Comment by shikhasingh1797** [comment]
Hello Sir
I implemented above solution but did not worked for me

(doc) PS D:\docquery> python
>>
Python 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]
:: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>>
>>> print(transformers.__version__)
4.23.0
>>>

(base) PS D:\docquery> conda activate doc
(doc) PS D:\docquery> docquery scan "What is the #1 post's title?"
website.html
>>
document-question-answering is already registered. Overwriting pipeline for
task document-question-answering...
WARNING:root:Unable to find tesseract: tesseract is not installed or it's
not in your PATH. See README file for more information..
Traceback (most recent call last):
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\runpy.py", line 193, in
_run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\N_B\Miniconda3\envs\doc\lib\runpy.py", line 85, in
_run_code
    exec(code, run_globals)
  File "C:\Users\N_B\Miniconda3\envs\doc\Scripts\docquery.exe\__main__.py",
line 7, in <module>
  File
"C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\cmd\__main__.py",
line 61, in main
    return args.func(args)
  File
"C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\cmd\scan.py",
line 67, in main
    docs.append((p, load_document(str(p), ocr_reader=args.ocr,
use_embedded_text=args.use_embedded_text)))
  File "pydantic\decorator.py", line 40, in
pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic\decorator.py", line 134, in
pydantic.decorator.ValidatedFunction.call
  File "pydantic\decorator.py", line 206, in
pydantic.decorator.ValidatedFunction.execute
  File
"C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\document.py",
line 261, in load_document
    return WebDocument(fpath)
  File
"C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\document.py",
line 193, in __init__
    self.driver = get_webdriver()
  File
"C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\web.py", line
128, in get_webdriver
    WEB_DRIVER = WebDriver()
  File
"C:\Users\N_B\Miniconda3\envs\doc\lib\site-packages\docquery\web.py", line
34, in __init__
    "Web imports are unavailable. You must install the [web] extra and
chrome or" " chromium system-wide."
ValueError: Web imports are unavailable. You must install the [web] extra
and chrome or chromium system-wide.
(doc) PS D:\docquery>

Thanks & Regards
Shikha Singh

**Comment by akashbiztechcs** [comment]
I was also facing the same issue but after apply the mentioned solution above **To downgrade the Transformer** it also worked for me.
Here is the SS of the downgrade Transformer :
![image](https://github.com/impira/docquery/assets/133968466/5470a7b2-6bc5-438b-82b5-ae3ca7376c04)

And here is the Actual execution of **docquery**. I know there is still error is showing but the good things is that now doc query is executing successfully.
![image](https://github.com/impira/docquery/assets/133968466/ba2af88e-9e50-4df1-ad0c-5f16f6842856)
