### ISSUE TITLE
Issue with docquery document pydantic

### ISSUE THREAD

**Issue by Priyankavinodh** [impira/docquery#68]
Hi I'm facing the issues with pydantic
  from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields' 

with the python 3.8, 3.9, 3.10 also . Please suggest the solutions for this

**Comment by EmbroseBhati** [comment]
use earlier version of pydantic
!pip install "pydantic==1.*"

**Comment by dhineshkoilpitchai** [comment]
Not able to install earlier version of pydantic==1.*

I am experiencing the same problem. If the issue has been resolved, please post it. This will assist me in moving forward.

**Comment by joaomaranhao** [comment]
@dhineshkoilpitchai
pip install pydantic==1.10

**Comment by khantthulinn** [comment]
I am implementing from my app in huggingface. 

In my requirements.txt, I have written like this. 

```
torch
pydantic==1.10
git+https://github.com/huggingface/transformers.git@21f6f58721dd9154357576be6de54eefef1f1818
git+https://github.com/impira/docquery.git@a494fe5af452d20011da75637aa82d246a869fa0#egg=docquery[web,donut]
```

But I am still having this error. How shall I do? How can I directly edit there? 

```
===== Application Startup at 2023-11-13 04:50:05 =====

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
Moving 0 files to the new cache system
0it [00:00, ?it/s]
0it [00:00, ?it/s]
image-classification is already registered. Overwriting pipeline for task image-classification...
Traceback (most recent call last):
  File "/home/user/app/app.py", line 12, in <module>
    from docquery.document import load_document, ImageDocument
  File "/home/user/.local/lib/python3.10/site-packages/docquery/document.py", line 12, in <module>
    from .ocr_reader import NoOCRReaderFound, OCRReader, get_ocr_reader
  File "/home/user/.local/lib/python3.10/site-packages/docquery/ocr_reader.py", line 6, in <module>
    from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/home/user/.local/lib/python3.10/site-packages/pydantic/fields.py)
```
https://huggingface.co/spaces/kenneth984/transcript_automation/

**Comment by yaroslavyaroslav** [comment]
@EmbroseBhati I'm good enough in pip dependencies, but is there a reason why this line isn't provided within the package itself?

**Comment by varun-affinsys** [comment]
For users using Python3.9 and Ubuntu, below combination works:
(After pip install docquery)
transformers==4.23
pydantic==1.10

**Comment by Spoomer** [comment]
For anyone with problems, I have here a dockerfile for a working docker image:

```
FROM python:3.11-slim

#Set work directory
WORKDIR /app

#Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential tesseract-ocr poppler-utils\
    && rm -rf /var/lib/apt/lists/*

#Install docquery and any other dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir docquery
RUN pip install --no-cache-dir transformers==4.23
RUN pip install --no-cache-dir pydantic==1.10

#Copy a initial PDF document to the container
RUN mkdir ./docs/
COPY ./init.pdf ./docs/init.pdf
# and run docquery to initialize the model
RUN docquery scan "date" ./docs/init.pdf

ENTRYPOINT ["docquery"]`
```

Run example:
`podman build -t docquery . `

`docker run --rm -v ./docs:/app/docs localhost/docquery:latest scan "date" ./docs/test.pdf`
